# Generated by Django 3.2.3 on 2021-05-27 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=30)),
                ('sub_time', models.TimeField(auto_now_add=True)),
                ('update_time', models.TimeField(auto_now=True)),
            ],
        ),
    ]
