# Generated by Django 3.2.3 on 2021-05-26 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s_id', models.IntegerField(default=0)),
                ('s_name', models.CharField(max_length=30)),
                ('s_price', models.IntegerField(default=0)),
                ('s_seller', models.CharField(max_length=30)),
                ('s_imageUrl', models.CharField(max_length=100)),
                ('s_description', models.CharField(max_length=100)),
            ],
        ),
    ]
